//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class theoremEntities : DbContext
    {
        public theoremEntities()
            : base("name=theoremEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comment> comments { get; set; }
        public DbSet<commenttable> commenttables { get; set; }
        public DbSet<math> maths { get; set; }
        public DbSet<member> members { get; set; }
    }
}
