//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.menus = new HashSet<menu>();
        }
    
        public int category_id { get; set; }
        public string category1 { get; set; }
    
        public virtual ICollection<menu> menus { get; set; }
    }
}
