//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class country_daily_promise
    {
        public string country { get; set; }
        public string country_code { get; set; }
        public System.DateTime C_date { get; set; }
        public Nullable<float> median_download_ratio { get; set; }
        public Nullable<float> median_upload_ratio { get; set; }
        public Nullable<int> total_surveys { get; set; }
    }
}
