//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class countries_list
    {
        public string country_code { get; set; }
        public string country { get; set; }
    }
}
