//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int ingr_id { get; set; }
        public string ingr_name { get; set; }
        public float init_qty { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<float> current_qty { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
