//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_backup
    {
        public int ingr_id { get; set; }
        public float qty_used { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime to { get; set; }
    }
}
