//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class kot
    {
        public int ID { get; set; }
        public int QTY { get; set; }
        public int TABLE_NO { get; set; }
        public System.DateTime TIME { get; set; }
        public int KOT_NO { get; set; }
    }
}
