//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class math
    {
        public int t_id { get; set; }
        public string thname { get; set; }
        public string thaim { get; set; }
        public string thdis { get; set; }
        public string thformula { get; set; }
        public string tag { get; set; }
    }
}
