//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int member_id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string Url { get; set; }
        public string Birthdate { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string profImage { get; set; }
        public string curcity { get; set; }
        public string hometown { get; set; }
        public string Interested { get; set; }
        public string language { get; set; }
        public string college { get; set; }
        public string highschool { get; set; }
        public string experiences { get; set; }
        public string arts { get; set; }
        public string aboutme { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public string year { get; set; }
        public string Stats { get; set; }
    }
}
