//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int ID { get; set; }
        public string item_name { get; set; }
        public int price { get; set; }
        public int category_id { get; set; }
        public bool chicken { get; set; }
    
        public virtual category category { get; set; }
    }
}
