//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_detail
    {
        public string Name { get; set; }
        public string addr_1 { get; set; }
        public string addr_2 { get; set; }
        public Nullable<int> pincode { get; set; }
        public string landmark { get; set; }
        public string city { get; set; }
        public int mob_no { get; set; }
    }
}
